version: '2'
services:
  # mysql:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: pass
  #   volumes:
  #     - db:/var/lib/mysql
  php:
    image: php:apache
    ports:
      - '8099:80'
    volumes:
      - ./html:/var/www/html
    # depends_on:
      # - mysql
volumes:
  db: